# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy CloudfoxSuit-Chat to S3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04 
    steps:
      - uses: actions/checkout@v2
      - uses: dopplerhq/cli-action@v1
      - name: set envs agent github actions
        run: doppller secrets download --no-file --format=docker >>$GITHUB_ENV;
        env: 
           DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRD }}
           
      - name: PRINT NOME
        run: echo $NOME 
      - uses: actions/setup-node@v1
        with:
          node-version: 12.21.0
      - name: INSTALL E BUILD
        run: npm install && npm run build
        env:
           CI: "false"
      - name: DEPLOY S3
        run: cd build && AWS_ACCESS_KEY_ID=${ACCESS_KEY} AWS_SECRET_ACCESS_KEY=${SECRET_KEY} aws s3 sync . s3://cloudfoxsuit-chat --acl public-read --delete
